apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  annotations:
  name: zz-install-trident-gcp-dev-de-placement
  namespace: policies
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
    - key: db-environment
      operator: In
      values:
      - dev
    - key: db-purpose
      operator: NotIn
      values:
      - acm
    - key: db-type
      operator: In
      values:
      - gcp
    - key: db-region
      operator: In
      values:
      - de
