apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  annotations:
  name: install-demo-app-placement
  namespace: policies
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
    - key: db-purpose
      operator: NotIn
      values:
      - acm
